
[charms]
	#Disable Charged Glow Up Charm
	disableGlowupCharm = false
	#Disable Charged Speed Charm
	disableSpeedCharm = false
	#Disable Charged Regeneration Charm
	disableRegenCharm = false
	#Disable Charged Absorption Charm
	disableAbsorptionCharm = false
	#Disable Charged Enchanted Totem Charm
	disableEnchTotemCharm = false
	#Disable Charged Totem Charm
	disableTotemCharm = false

[tweaks]
	#Charged Regeneration Charm effect amplifier.
	#Range: 0 ~ 255
	regenAmplifier = 0
	#Duration in seconds for the Charged Regeneration Charm effect.
	#Range: 1 ~ 300
	regenDuration = 15
	#Cooldown in seconds for the Charged Speed Charm.
	#Range: 0 ~ 360
	speedCooldown = 120
	#Charged Absorption Charm effect amplifier.
	#Range: 0 ~ 255
	absorptionAmplifier = 0
	#Duration in seconds for the Charged Glow Up Charm effect.
	#Range: 1 ~ 300
	glowUpDuration = 30
	#Duration in seconds for the Charged Speed Charm effect.
	#Range: 1 ~ 360
	speedDuration = 180
	#Duration in seconds for the Charged Absorption Charm effect.
	#Range: 1 ~ 300
	absorptionDuration = 5
	#Cooldown in seconds for the Charged Absorption Charm.
	#Range: 0 ~ 300
	absorptionCooldown = 20
	#Low health percentage to trigger Charged Regeneration Charm.
	#Range: 0.2 ~ 0.8
	regenPercentage = 0.35

